# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-10 05:20
from __future__ import unicode_literals

import apps.loginreg.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, validators=[apps.loginreg.models.nameValidation])),
                ('email', models.CharField(max_length=45, validators=[apps.loginreg.models.emailValidation])),
                ('password', models.CharField(max_length=25, validators=[apps.loginreg.models.passwordValidation])),
                ('confirm_password', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
